---
abstract: 'Schema class scaffold generator for DBIx::Class'
author:
  - 'Graham Barr'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mesoderm
requires:
  DBI: 0
  Data::Dumper: 0
  File::Temp: 0
  Lingua::EN::Inflect::Number: 0
  Moose: 0.98
  MooseX::Getopt: 0
  MooseX::Types::Path::Class: 0
  Path::Class: 0
  SQL::Translator: 0.11008
resources:
  repository: git://github.com/gbarr/Mesoderm.git
version: 0.122290
